# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 03d6ede17013c4de85d90aa510c2ddf0628a6acd7ac8aeb044d6c9386382fbc665457d4a2dbbcd36e99d96575577287480cf6864d32e74c6d4d502a2146fb73a

test:
  domain_name: example.com 
  secret_key_base: 36af50caca2b56e92ae26d7259a76d3a9826a346b4fe95e57865f7861d75ba4d18fe5b9d40d072370e226c1fc4d23a1bb67dbd18aa04d84604b6182e96455acc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
